baseURL = "https://clever-jepsen-cd1ca9.netlify.app"
languageCode = "en-us"
title = "Zachary Montoya"
theme = "hugo-resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
address = "Los Angeles, CA"
email = "zacharycmontoya@gmail.com"
favicon = "/favicon.ico"
firstName = "Zachary"
lastName = "Montoya"
phone = "1-555-555-1234"
profileImage = "images/profile.jpg"
showBlog = false
showEducation = true
showExperience = true
showOpenSource = true
showProjects = false
showPublications = false
showQr = false
showSkills = false

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/zacharymontoya/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/zacharycmontoya"
name = "GitHub"

[[params.handles]]
link = "https://twitter.com/ZacharyCMontoya"
name = "Twitter"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
